server:
  port: 8088

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost/db_kuaidi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hsl521xjc
    #    password: mlx120011629

    # 使用druid数据源
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.graduate.luggagedelivery.rest_server.dao: DEBUG